name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # strategy:
    #   matrix:
    #     image: [ linux/amd64, linux/arm64, linux/arm/v5, linux/arm/v6, linux/arm/v7, linux/386, darwin/amd64, darwin/arm64, windows/amd64, windows/386 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        source .versions
        docker build . --file Dockerfile --tag ghcr.io/navidrome/cross-taglib:$(date +%s) \
          --build-arg TAGLIB_VERSION=${TAGLIB_VERSION} 
          --build-arg TAGLIB_SHA=${TAGLIB_SHA} \
          --build-arg RELEASE_VERSION=${RELEASE_VERSION} \
          --output "./dist" \
          --target "artifact" .

