name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
     matrix:
       platform: [ linux/amd64, linux/arm64 ]
    #         platform: [ linux/amd64, linux/arm64, linux/arm/v5, linux/arm/v6, linux/arm/v7, linux/386, darwin/amd64, darwin/arm64, windows/amd64, windows/386 ]
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - uses: actions/checkout@v4

#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v3
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        labels: |
          maintainer=deluan
        images: |
          name=ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: ${{ matrix.platform }}
#        push: true
        outputs: |
          type=local,dest=./dist
        target: artifact
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          TAGLIB_VERSION=2.0.2
          TAGLIB_SHA=e3de03501ff66221d1f1f971022b248d5b38ba06
          RELEASE_VERSION=0

    - uses: actions/upload-artifact@v4
      with:
        name: taglib-2.0.2-1.${{ matrix.platform }}.zip
        path: ./dist
        retention-days: 7

#    - name: Build the Docker image
#      run: |
#        source .versions
#        docker build . --file Dockerfile --tag ghcr.io/navidrome/cross-taglib:$(date +%s) \
#          --build-arg TAGLIB_VERSION=${TAGLIB_VERSION}
#          --build-arg TAGLIB_SHA=${TAGLIB_SHA} \
#          --build-arg RELEASE_VERSION=${RELEASE_VERSION} \
#          --output "./dist" \
#          --target "artifact" .

